### ISSUE TITLE
change to secure hea-www 

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-webcode#26]
I'm looking at the publish code a bit (don't ask) and I see things like this in the style sheets

    xmlns:djb="http://hea-www.harvard.edu/~dburke/xsl/"
    xmlns:extfuncs="http://hea-www.harvard.edu/~dburke/xsl/extfuncs"

Should we change those to https://hea-www now?

**Comment by DougBurke** [comment]
These are purely names - they are not resolved at all. So we could just say
"bob" and "fred" (although maybe they need to be a URI?). So I don't think
they need to be updated.

Doug

**Comment by kglotfelty** [comment]
I was guessing that was the case, just not sure if it was related to the `entity` thing that broke earlier.
