### ISSUE TITLE
Line number in `id` link warning

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-webcode#35]
@DougBurke , is there any way to get the line number when this warning is generated?

https://github.com/cxcsds/ciao-webcode/blob/5c77997cbe6e832da21251d9b7b444ed5848792c/links.xsl#L2610

**Comment by DougBurke** [comment]
I think the answer varies from "no" to "I don't know but I doubt it'd be pretty".  What I was briefly thinking about recently was to add information which would at least include the id message, something like the untested

```
<xsl:messge terminate="no">Change &lt;id name=<xsl:value-of "@name"/> <xsl:apply-templates/>&gt; to use id=... attribute</xsl:message>
```
